version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: smartcv_db
      POSTGRES_USER: smartcv_user
      POSTGRES_PASSWORD: smartcv_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://smartcv_user:smartcv_password@postgres/smartcv_db
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./generated_pdfs:/app/generated_pdfs

  celery_worker:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info --queues=pdf_generation,email_sending
    environment:
      - DATABASE_URL=postgresql://smartcv_user:smartcv_password@postgres/smartcv_db
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./generated_pdfs:/app/generated_pdfs

  celery_beat:
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://smartcv_user:smartcv_password@postgres/smartcv_db
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
