# render.yaml - Render service configuration
services:
  - type: web
    name: smartcv-backend
    runtime: python3
    plan: free  # or starter/pro
    buildCommand: ./build.sh
    startCommand: ./start.sh
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        fromDatabase:
          name: smartcv-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: smartcv-redis
          property: connectionString

  - type: postgres
    name: smartcv-db
    plan: free
    databaseName: smartcv
    user: smartcv

  - type: redis
    name: smartcv-redis
    plan: free
