#!/bin/bash

# Render Environment Setup for SmartCV Backend
# Run this script to set environment variables or copy these to Render dashboard

echo "Setting up SmartCV Backend Environment Variables for Render..."
echo ""
echo "Copy these environment variables to your Render service:"
echo ""
echo "=== REQUIRED VARIABLES ==="
echo "DATABASE_URL = your_aiven_postgresql_connection_string_here"
echo "SECRET_KEY = your_super_secret_jwt_key_here"
echo "ALGORITHM = HS256"
echo "ACCESS_TOKEN_EXPIRE_MINUTES = 30"
echo "ENVIRONMENT = production"
echo "DEBUG = false"
echo "UPLOAD_DIR = /tmp/uploads/"
echo "MAX_FILE_SIZE = 5242880"
echo ""
echo "=== OPTIONAL VARIABLES (can be empty) ==="
echo "ALLOWED_HOSTS = [\"https://your-frontend-url.vercel.app\"]"
echo "REDIS_URL = "
echo "CELERY_BROKER_URL = "
echo "CELERY_RESULT_BACKEND = "
echo "STRIPE_SECRET_KEY = "
echo "STRIPE_PUBLISHABLE_KEY = "
echo "STRIPE_WEBHOOK_SECRET = "
echo "SMTP_HOST = smtp.gmail.com"
echo "SMTP_PORT = 587"
echo "SMTP_USER = "
echo "SMTP_PASSWORD = "
echo "GEMINI_API_KEY = "
echo ""
echo "Instructions:"
echo "1. Go to your Render dashboard"
echo "2. Select your SmartCV backend service"
echo "3. Go to 'Environment' tab"
echo "4. Add each variable above"
echo "5. Deploy your service"
echo ""
echo "After adding variables, your service should start successfully!"
